
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
    name: credentials.dapr.io
    labels:
        app.kubernetes.io/part-of: "dapr"
spec:
  group: dapr.io
  names:
    kind: Credential
    listKind: Credentials
    plural: credentials
    singluar: credential
    categories:
    - dapr
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Credential describes a Dapr credential type.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          scopes:
            items:
              type: string
            type: array
          spec:
            description: CredentialSpec is the spec for a credential.
            properties:
              providers:
                azureVisualStudioCredentialProvider:
                  description: An Azure credential provider utilizing the token provided by Visual Studio.
                  type: object
                azureVisualStudioCodeCredentialProvider:
                  description: An Azure credential provider utilizing the token provided by Visual Studio Code.
                  type: object
                azureClientCredentialProvider:
                  description: An Azure credential provider utilizing a client secret credential to authenticate.
                  properties:
                    tenantId:
                      description: Microsoft Entra tenant ID of the service principal
                      type: string
                    clientId:
                      description: Microsoft Entra Client ID (application ID) of the service principal
                      type: string
                    clientSecret:
                      description: Client secret (application password) generated for the App Registration
                      type: string
                  required:
                  - tenantId
                  - clientId
                  - clientSecret
                  type: object
                azureCertificateCredentialProvider:
                  description: An Azure credential provider utilizing a certificate to authenticate.
                  properties:
                    tenantId:
                      description: Microsoft Entra tenant ID of the service principal
                      type: string
                    clientId:
                      description: Microsoft Entra Client ID (application ID) of the service principal
                      type: string
                    certificate:
                      description: The authentication X509 certificate and private key (in PFX/PKCS#12 format)
                      type: string
                    certificateFile:
                      description: Path to the PFX/PKCS#12 file containing the certificate and private key
                      type: string
                    certificatePassword:
                      description: Password for the certificate if encrypted
                      type: string
                  required:
                  - tenantId
                  - clientId
                  type: object
                azureManagedIdentityCredentialProvdier:
                  description: An Azure credential provider representing either a system-assigned or user-assigned identity.
                  properties:
                    clientId:
                      description: User-assigned identity client ID
                      type: string
                  type: object
                azureWorkloadIdentityCredentialProvider:
                  description: An Azure credential provider representing a workload identity as used with AKS.
                  type: object
                azureCliCredentialProvider:
                  description: An Azure credential provider utilizing credentials sourced from successful authentication against the Azure CLI.
                  type: object
                type: array
              type:
                type: string
              version:
                type: string
            required:
            - providers
            - type
            - version
        type: object
    served: true
    storage: true

